# Generated by Django 4.2.26 on 2026-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_notification_like'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games_played',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.game'),
        ),
    ]
