# Generated by Django 4.2.26 on 2026-02-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.CharField(blank=True, help_text='e.g. $1000 or Gaming Gear', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='upcoming', max_length=20),
        ),
    ]
