# Generated by Django 4.2.26 on 2026-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tournament_game_tournament_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique team username (e.g. @og_team)', null=True, unique=True),
        ),
    ]
